# Setup
title:               Effective Java summary
tagline:             'By Doo and Cheolho'
description:         'Effective Java 3/E summary by Doo and Cheolho.'
url:                 https://ej20.cjeon.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Doo Lim, Cheolho Jeon
  email:             ej20@cjeon.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
